CREATE TABLE IF NOT EXISTS `policy_crawler_article` (
  `policy_crawler_article_id` varchar(36) NOT NULL COMMENT '主键',
  `source_code` varchar(50) NOT NULL COMMENT '来源编码',
  `source_item_id` varchar(128) NOT NULL COMMENT '来源稳定ID',
  `source_name` varchar(100) NOT NULL COMMENT '来源名称',
  `title` varchar(1000) NOT NULL COMMENT '政策标题',
  `project_name` varchar(1000) NOT NULL COMMENT '项目名称',
  `policy_level` varchar(100) DEFAULT NULL COMMENT '政策层级',
  `publish_dept` varchar(500) DEFAULT NULL COMMENT '发文部门',
  `document_no` varchar(200) DEFAULT NULL COMMENT '发文文号',
  `publish_date` date DEFAULT NULL COMMENT '发文日期',
  `apply_start` date DEFAULT NULL COMMENT '申报开始时间',
  `apply_end` date DEFAULT NULL COMMENT '申报结束时间',
  `content_html` longtext NOT NULL COMMENT '标准化正文HTML',
  `original_url` varchar(2000) NOT NULL COMMENT '原文链接',
  `attachments_json` longtext COMMENT '附件链接JSON',
  `raw_json` longtext COMMENT '来源原始JSON',
  `content_hash` char(64) NOT NULL COMMENT '标准化正文SHA256',
  `kms_document_id` char(32) NOT NULL COMMENT '确定性KMS文档ID',
  `base_id` varchar(100) NOT NULL COMMENT '目标知识库ID',
  `kms_payload_json` longtext NOT NULL COMMENT '已验证KMS请求快照',
  `crawl_status` varchar(32) NOT NULL DEFAULT 'success' COMMENT '抓取状态',
  `kms_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'KMS状态',
  `content_update_status` varchar(32) NOT NULL DEFAULT 'not_needed' COMMENT '正文覆盖更新状态',
  `content_update_error` text COMMENT '正文覆盖更新错误摘要',
  `content_updated_at` datetime DEFAULT NULL COMMENT '正文覆盖更新时间',
  `kms_result_code` varchar(20) DEFAULT NULL COMMENT 'KMS业务码',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT 'KMS重试次数',
  `last_error` text COMMENT '最近错误摘要',
  `first_seen_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `crawled_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pushed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`policy_crawler_article_id`),
  UNIQUE KEY `uk_policy_crawler_source` (`source_code`,`source_item_id`,`base_id`),
  UNIQUE KEY `uk_policy_crawler_kms_document` (`kms_document_id`,`base_id`),
  KEY `idx_policy_crawler_kms_status` (`kms_status`,`updated_at`),
  KEY `idx_policy_crawler_content_update_status` (`content_update_status`,`updated_at`),
  KEY `idx_policy_crawler_publish_date` (`publish_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='独立政策爬虫文章及KMS入库状态';

CREATE TABLE IF NOT EXISTS `policy_crawler_run` (
  `run_id` char(32) NOT NULL COMMENT '批次ID',
  `trigger_type` varchar(20) NOT NULL COMMENT 'manual/schedule/retry',
  `status` varchar(20) NOT NULL COMMENT 'queued/running/completed/stopped/failed',
  `task_codes_json` text NOT NULL COMMENT '任务编码JSON',
  `dry_run` decimal(1,0) NOT NULL DEFAULT 1 COMMENT '是否预检',
  `total` int NOT NULL DEFAULT 0,
  `processed` int NOT NULL DEFAULT 0,
  `succeeded` int NOT NULL DEFAULT 0,
  `skipped` int NOT NULL DEFAULT 0,
  `failed` int NOT NULL DEFAULT 0,
  `current_item` varchar(128) DEFAULT NULL,
  `message` varchar(1000) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  PRIMARY KEY (`run_id`),
  KEY `idx_policy_crawler_run_created` (`created_at`),
  KEY `idx_policy_crawler_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='政策爬虫运行批次';

CREATE TABLE IF NOT EXISTS `policy_crawler_run_item` (
  `run_item_id` char(32) NOT NULL COMMENT '明细ID',
  `run_id` char(32) NOT NULL COMMENT '批次ID',
  `task_code` varchar(64) NOT NULL COMMENT '任务编码',
  `source_code` varchar(50) NOT NULL COMMENT '来源编码',
  `source_item_id` varchar(128) NOT NULL COMMENT '来源稳定ID',
  `policy_crawler_article_id` varchar(36) DEFAULT NULL COMMENT '文章ID',
  `kms_document_id` char(32) DEFAULT NULL COMMENT 'KMS文档ID',
  `status` varchar(32) NOT NULL COMMENT 'success/skipped/failed/source_empty/dry_run',
  `phase` varchar(32) NOT NULL COMMENT 'discover/fetch/store/kms',
  `message` varchar(2000) DEFAULT NULL,
  `kms_result_code` varchar(20) DEFAULT NULL,
  `duration_ms` int DEFAULT NULL,
  `retry_count` int NOT NULL DEFAULT 0,
  `error_detail` text COMMENT '脱敏错误详情',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` datetime DEFAULT NULL,
  PRIMARY KEY (`run_item_id`),
  KEY `idx_policy_crawler_run_item_run` (`run_id`,`created_at`),
  KEY `idx_policy_crawler_run_item_status` (`status`,`phase`),
  KEY `idx_policy_crawler_run_item_article` (`policy_crawler_article_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='政策爬虫运行明细';
